# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 181b01f97ac119df4c4095c6efc30729f45c0ce88d29007842b18ab61500fa86f33c1dee940574325b9e802bfa62c6dabce7618490882ab8506909b4cfc614f8

test:
  secret_key_base: 6d39b70a0faa8458cea38715c2adb143dbf02404472d15ebea90c48e44c323a19d0e79f90caa6d3cd15b3bb20efb378097ad5a70b3851ab55405a99a60a351fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
